version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: budgetbuddy-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: budgetbuddy
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend
    container_name: budgetbuddy-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/budgetbuddy
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_key_change_in_production}
      - NODE_ENV=production
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: budgetbuddy-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongodb_data:
